/* This file contains the SQL script used to create the `CONTATOS` table, the generator, and the trigger for auto-incrementing the `ID` field. */

CREATE TABLE CONTATOS
(
  ID INTEGER NOT NULL PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  TELEFONE VARCHAR(20),
  OBSERVACOES BLOB SUB_TYPE TEXT
);

CREATE GENERATOR GEN_CONTATOS_ID;

CREATE TRIGGER BI_CONTATOS FOR CONTATOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CONTATOS_ID, 1);
END
 ;

COMMIT ;
